site_name: Bike Sharing
theme:
  name: material
  palette:
    primary: green
  features:
    - content.code.annotate
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
